version: 2

jobs:
  build:
    working_directory: ~/tol
    docker:
      - image: circleci/clojure:lein-2.8.1
    environment:
      LEIN_ROOT: nbd
      LC_ALL: C
    steps:
      - checkout
      - restore_cache:
          key: tol-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: tol-{{ checksum "project.clj" }}
      - run: wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O ~/phantomjs-2.1.1.tar.bz2
      - run: mkdir ~/phantomjs && tar -xvf ~/phantomjs-2.1.1.tar.bz2 -C ~/phantomjs
      - run: sudo mv ~/phantomjs/phantomjs-2.1.1-linux-x86_64 /usr/local/share/phantomjs-2.1.1-linux-x86_64
      - run: sudo ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/share/phantomjs
      - run: sudo ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
      - run: sudo ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/phantomjs
      - run: phantomjs --version
      - run: lein test
      - run: lein cljs-tests
      - run: lein cloverage --fail-threshold 95
      - run: lein kibit
